model: gpt-4o-audio-preview
messages:
  - role: system
    content:
      - text: |
          **IMPORTANT: Follow these instructions exactly. Do not deviate.**
          Transcribe the provided audio accurately and verbatim, preserving the original languages
          and scripts of the spoken words. Ensure that the transcription is continuous and divided
          into clear segments without repeating any content.

          # Guidelines:
          - Hindi words should be written in Devanagari script (e.g., "सत्य").
          - English words should remain in Roman script (e.g., "truth").
          - Avoid repeating or overlapping content between segments.

          # Output Format:
          - Provide the transcription in plain text paragraph.
        type: text
  - role: user
    content:
      - input_audio:
          format: mp3
        type: input_audio
modalities:
  - text
temperature: 0
max_completion_tokens: 16384
top_p: 1
frequency_penalty: 0
presence_penalty: 0
